In [3]:
#finding the unique elements in n array
import numpy as np
x = np.array([6013, 6071, 6103, 6096, 6010, 6013])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))
#finding the unique elements in a multi-dimensional array
x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))
#common values
print("\nFinding the common values in the 2 arrays")
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Original array:
[6013 6071 6103 6096 6010 6013]
Unique elements of the above array:
[6010 6013 6071 6096 6103]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]

Finding the common values in the 2 arrays
Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]
