In [12]:
#multiplication of 2 square matrix
import numpy as np
p = [[1, 2], [3, 4]]
q = [[8, 7], [6, 5]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the matrix multiplication:")
print(result1)
#determinant of a square matrix
print("\nDeterminant of a square matrix:")
import numpy as np
from numpy import linalg as LA
a = np.array([[1, 2], [3, 4]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))
#Einstein summation
print("\nEinstein's Summation over an array:-")
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Original 1-d arrays:")
print(a)
print(b)
result =  np.einsum("n,n", a, b)
print("Einstein’s summation convention of the said arrays:")
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
result = np.einsum("mk,kn", x, y)
print("Einstein’s summation convention of the said arrays:")
print(result)

original matrix:
[[1, 2], [3, 4]]
[[8, 7], [6, 5]]
Result of the matrix multiplication:
[[20 17]
 [48 41]]

Determinant of a square matrix:
Original 2-d array
[[1 2]
 [3 4]]
Determinant of the said 2-D array:
-2.0000000000000004

Einstein's Summation over an array:-
Original 1-d arrays:
[1 2 3]
[4 5 6]
Einstein’s summation convention of the said arrays:
32
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Einstein’s summation convention of the said arrays:
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]
