In [4]:
#mathematical operations using numpy
import numpy as np
print("Add:")
print(np.add(6013, 5060))
print("Subtract:")
print(np.subtract(6013, 5060))
print("Multiply:")
print(np.multiply(6013, 5060))
print("Divide:")
print(np.divide(6013, 5060))
#exponentiation
print("\nExponentiation:")
import numpy as np
l1 = np.log(1e-50)
l2 = np.log(2.5e-50)
print("Logarithm of the sum of exponentiations:")
print(np.logaddexp(l1, l2))
print("Logarithm of the sum of exponentiations of the inputs in base-2:")
print(np.logaddexp2(l1, l2))
#abs() function
print("\nabsolute function")
import numpy as np
x = np.array([-10.2, 122.2, .20])
print("Original array:")
print(x)
print("Element-wise absolute value:")
print(np.absolute(x))
#flooring,ceiling,truncation
print("\nflooring,ceiling,truncation")
import numpy as np
x = np.array([-60.13, -60.71, -61.03, 60.96, 60.10, 6002, 6082])
print("Original array:")
print(x)
print("Floor values of the above array elements:")
print(np.floor(x))
print("Ceil values of the above array elements:")
print(np.ceil(x))
print("Truncated values of the above array elements:")
print(np.trunc(x))

Add:
11073
Subtract:
953
Multiply:
30425780
Divide:
1.1883399209486165

Exponentiation:
Logarithm of the sum of exponentiations:
-113.87649168120691
Logarithm of the sum of exponentiations of the inputs in base-2:
-113.59955522772194

absolute function
Original array:
[-10.2 122.2   0.2]
Element-wise absolute value:
[ 10.2 122.2   0.2]

flooring,ceiling,truncation
Original array:
[ -60.13  -60.71  -61.03   60.96   60.1  6002.   6082.  ]
Floor values of the above array elements:
[ -61.  -61.  -62.   60.   60. 6002. 6082.]
Ceil values of the above array elements:
[ -60.  -60.  -61.   61.   61. 6002. 6082.]
Truncated values of the above array elements:
[ -60.  -60.  -61.   60.   60. 6002. 6082.]
