In [5]:
#finding the roots of the polynomial
print("\nroots of the \nx2-2x+1\nx4-12x3+10x2+7x=10\nx2-5x+6")
import numpy as np
print("Roots of the first polynomial:")
print(np.roots([1, -2, 1]))
print("Roots of the second polynomial:")
print(np.roots([1, -12, 10, 7, -10]))
print("Roots of the third polynomial:")
print(np.roots([1,-5,6]))
#computing the values of the polynomial
print("\nto find the polynomial computed value:")
import numpy as np
print("Polynomial value when x = 2:")
print(np.polyval([1, -2, 1], 2))
print("Polynomial value when x = 3:")
print(np.polyval([1, -12, 10, 7, -10], 3))
#polynomial operations
print("\npolynomial add,sub,mult,div")
from numpy.polynomial import polynomial as P
x = (10,20,30)
y = (30,40,50)
print("Add one polynomial to another:")
print(P.polyadd(x,y))
print("Subtract one polynomial from another:")
print(P.polysub(x,y))
print("Multiply one polynomial by another:")
print(P.polymul(x,y))
print("Divide one polynomial by another:")
print(P.polydiv(x,y))


roots of the 
x2-2x+1
x4-12x3+10x2+7x=10
x2-5x+6
Roots of the first polynomial:
[1. 1.]
Roots of the second polynomial:
[11.04461946+0.j        -0.8711421 +0.j         0.91326132+0.4531004j
  0.91326132-0.4531004j]
Roots of the third polynomial:
[3. 2.]

to find the polynomial computed value:
Polynomial value when x = 2:
1
Polynomial value when x = 3:
-142

polynomial add,sub,mult,div
Add one polynomial to another:
[40. 60. 80.]
Subtract one polynomial from another:
[-20. -20. -20.]
Multiply one polynomial by another:
[ 300. 1000. 2200. 2200. 1500.]
Divide one polynomial by another:
(array([0.6]), array([-8., -4.]))
