In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([10,11,12])
print('First array:')
print(a)
print('Second array')
print(b)
print('Sum of 2 arrays:')
print(a+b)

First array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Second array
[10 11 12]
Sum of 2 arrays:
[[11 13 15]
 [14 16 18]
 [17 19 21]]
