In [1]:
#numpy iterating over an array:
import numpy as np
a=np.arange(0,100,10)
a=a.reshape(2,5)
print('Original array is:')
print(a)
print('Transpose of the original array is:')
b=a.T
print(b)
print('Modified array is:')
for x in np.nditer(b):
    print(x,)

Original array is:
[[ 0 10 20 30 40]
 [50 60 70 80 90]]
Transpose of the original array is:
[[ 0 50]
 [10 60]
 [20 70]
 [30 80]
 [40 90]]
Modified array is:
0
10
20
30
40
50
60
70
80
90
