In [1]:
#evenly spaced numbers in an array
import numpy as np
a=np.arange(10)
print('before changing shape')
print(a)
a.ndim
a.shape=(2,5)
print('after changing shape')
print(a)

before changing shape
[0 1 2 3 4 5 6 7 8 9]
after changing shape
[[0 1 2 3 4]
 [5 6 7 8 9]]
